### ISSUE TITLE
ドメイン変更＆httpsを使う

### ISSUE THREAD

**Issue by sotetsuk** [sotetsuk/sotetsuk.github.io#3]
# WHY

SEO的な観点でもHTTPS対応は重要。
sotets.uk ドメインを取得したこともあり、ついでにHTTPS対応を行う。
# HOW

こちらの記事を参考にやってみる: [カスタムドメインの GitHub Pages で HTTPS](http://qiita.com/superbrothers/items/95e5723e9bd320094537)
# TODO
- [x] sotets.uk ドメインに変更 ＆ HTTPS対応
- [x] sotetsuk.net から sotets.uk ドメインへリダイレクトするようにする
- [x] 色んなサイトへ書いたURLを変更して回る
  - [x] 自分のサイト
  - [x] cv
  - [x] master_thesis
  - [x] qiita
  - [x] codeiq
  - [x] wantedly
  - [x] linkedin
  - [x] ishiilab
  - [x] algo-rl-ja

**Comment by sotetsuk** [comment]
TODO: 
- [x] digが通るようになるのを待つ
- [x] /のCNAMEを変更する（これでsotets.uk）からアクセスできるはず（？）

**Comment by sotetsuk** [comment]
あとは[Qiita記事](http://qiita.com/superbrothers/items/95e5723e9bd320094537)に従ってHTTPSを設定した。
HSTSまで設定を行った。
